[0m00:55:57.014136 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5A216C3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5A2FE4140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5A548C380>]}


============================== 00:55:57.014136 | 039b5a53-01c6-49ba-9b95-dcdfe3dc2a8a ==============================
[0m00:55:57.014136 [info ] [MainThread]: Running with dbt=1.10.3
[0m00:55:57.014136 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\mukun\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init netflix', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:55:57.064553 [debug] [MainThread]: Starter project path: C:\Data Engineering\DBT Projec\DBT\venv\Lib\site-packages\dbt\include\starter_project
[0m00:55:57.080551 [info ] [MainThread]: 
Your new dbt project "netflix" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:55:57.080551 [info ] [MainThread]: Setting up your profile.
[0m00:56:58.272135 [info ] [MainThread]: Profile netflix written to C:\Users\mukun\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:56:58.272135 [debug] [MainThread]: Command `dbt init` succeeded at 00:56:58.272135 after 61.38 seconds
[0m00:56:58.272135 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5A5102DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5A737D640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5A7C75520>]}
[0m00:56:58.272135 [debug] [MainThread]: Flushing usage events
[0m00:56:59.265415 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:57:33.466492 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BAEB4920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8B87F42F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8B84E5190>]}


============================== 00:57:33.476341 | da7e6ffb-5d84-4b05-9abd-d30f582becac ==============================
[0m00:57:33.476341 [info ] [MainThread]: Running with dbt=1.10.3
[0m00:57:33.476341 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mukun\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:57:33.516109 [info ] [MainThread]: dbt version: 1.10.3
[0m00:57:33.516109 [info ] [MainThread]: python version: 3.12.7
[0m00:57:33.520552 [info ] [MainThread]: python path: C:\Data Engineering\DBT Projec\DBT\venv\Scripts\python.exe
[0m00:57:33.521677 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m00:57:34.136400 [info ] [MainThread]: Using profiles dir at C:\Users\mukun\.dbt
[0m00:57:34.136400 [info ] [MainThread]: Using profiles.yml file at C:\Users\mukun\.dbt\profiles.yml
[0m00:57:34.136400 [info ] [MainThread]: Using dbt_project.yml file at C:\Data Engineering\DBT Projec\DBT\dbt_project.yml
[0m00:57:34.136400 [info ] [MainThread]: adapter type: snowflake
[0m00:57:34.136400 [info ] [MainThread]: adapter version: 1.9.0
[0m00:57:34.136400 [info ] [MainThread]: Configuration:
[0m00:57:34.136400 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m00:57:34.136400 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:57:34.136400 [info ] [MainThread]: Required dependencies:
[0m00:57:34.136400 [debug] [MainThread]: Executing "git --help"
[0m00:57:34.155774 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m00:57:34.156770 [info ] [MainThread]: Connection:
[0m00:57:34.158766 [info ] [MainThread]:   account: VURBITQ-KN08569
[0m00:57:34.159762 [info ] [MainThread]:   user: dbt
[0m00:57:34.160458 [info ] [MainThread]:   database: MOVIELENS.RAW
[0m00:57:34.160458 [info ] [MainThread]:   warehouse: COMPUTE_WH
[0m00:57:34.160458 [info ] [MainThread]:   role: TRANSFORM
[0m00:57:34.160458 [info ] [MainThread]:   schema: RAW
[0m00:57:34.160458 [info ] [MainThread]:   authenticator: None
[0m00:57:34.160458 [info ] [MainThread]:   oauth_client_id: None
[0m00:57:34.160458 [info ] [MainThread]:   query_tag: None
[0m00:57:34.160458 [info ] [MainThread]:   client_session_keep_alive: False
[0m00:57:34.160458 [info ] [MainThread]:   host: None
[0m00:57:34.160458 [info ] [MainThread]:   port: None
[0m00:57:34.160458 [info ] [MainThread]:   proxy_host: None
[0m00:57:34.173337 [info ] [MainThread]:   proxy_port: None
[0m00:57:34.173337 [info ] [MainThread]:   protocol: None
[0m00:57:34.173337 [info ] [MainThread]:   connect_retries: 1
[0m00:57:34.173337 [info ] [MainThread]:   connect_timeout: None
[0m00:57:34.173337 [info ] [MainThread]:   retry_on_database_errors: False
[0m00:57:34.173337 [info ] [MainThread]:   retry_all: False
[0m00:57:34.173337 [info ] [MainThread]:   insecure_mode: False
[0m00:57:34.173337 [info ] [MainThread]:   reuse_connections: True
[0m00:57:34.173337 [info ] [MainThread]: Registered adapter: snowflake=1.9.0
[0m00:57:34.543892 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m00:57:37.059780 [debug] [MainThread]: Using snowflake connection "debug"
[0m00:57:37.059780 [debug] [MainThread]: On debug: select 1 as id
[0m00:57:37.059780 [debug] [MainThread]: Opening a new connection, currently in state init
[0m00:57:39.403289 [debug] [MainThread]: SQL status: SUCCESS 1 in 2.349 seconds
[0m00:57:39.403289 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m00:57:39.418719 [info ] [MainThread]: [31m2 checks failed:[0m
[0m00:57:39.418719 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Data Engineering\DBT Projec\DBT\dbt_project.yml> not found

[0m00:57:39.418719 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m00:57:39.433156 [debug] [MainThread]: Command `dbt debug` failed at 00:57:39.433156 after 6.15 seconds
[0m00:57:39.434894 [debug] [MainThread]: Connection 'debug' was left open.
[0m00:57:39.438062 [debug] [MainThread]: On debug: Close
[0m00:57:39.870294 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BB72B980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BD7BDFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BD9048F0>]}
[0m00:57:39.872289 [debug] [MainThread]: Flushing usage events
[0m00:57:40.835934 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:59:39.380280 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021DE2A9ACF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021DE2CB4C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021DE53E5940>]}


============================== 00:59:39.385293 | 56efaf9a-63a9-40af-b917-a748b97bf6b7 ==============================
[0m00:59:39.385293 [info ] [MainThread]: Running with dbt=1.10.3
[0m00:59:39.386263 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mukun\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:59:39.410969 [info ] [MainThread]: dbt version: 1.10.3
[0m00:59:39.410969 [info ] [MainThread]: python version: 3.12.7
[0m00:59:39.410969 [info ] [MainThread]: python path: C:\Data Engineering\DBT Projec\DBT\venv\Scripts\python.exe
[0m00:59:39.410969 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m00:59:39.965722 [info ] [MainThread]: Using profiles dir at C:\Users\mukun\.dbt
[0m00:59:39.965722 [info ] [MainThread]: Using profiles.yml file at C:\Users\mukun\.dbt\profiles.yml
[0m00:59:39.965722 [info ] [MainThread]: Using dbt_project.yml file at C:\Data Engineering\DBT Projec\DBT\dbt_project.yml
[0m00:59:39.965722 [info ] [MainThread]: adapter type: snowflake
[0m00:59:39.965722 [info ] [MainThread]: adapter version: 1.9.0
[0m00:59:39.965722 [info ] [MainThread]: Configuration:
[0m00:59:39.965722 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m00:59:39.976875 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:59:39.978235 [info ] [MainThread]: Required dependencies:
[0m00:59:39.978725 [debug] [MainThread]: Executing "git --help"
[0m00:59:39.978725 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m00:59:39.978725 [info ] [MainThread]: Connection:
[0m00:59:39.978725 [info ] [MainThread]:   account: VURBITQ-KN08569
[0m00:59:39.978725 [info ] [MainThread]:   user: dbt
[0m00:59:39.978725 [info ] [MainThread]:   database: MOVIELENS
[0m00:59:39.978725 [info ] [MainThread]:   warehouse: COMPUTE_WH
[0m00:59:39.978725 [info ] [MainThread]:   role: TRANSFORM
[0m00:59:39.978725 [info ] [MainThread]:   schema: RAW
[0m00:59:39.978725 [info ] [MainThread]:   authenticator: None
[0m00:59:39.978725 [info ] [MainThread]:   oauth_client_id: None
[0m00:59:39.978725 [info ] [MainThread]:   query_tag: None
[0m00:59:39.978725 [info ] [MainThread]:   client_session_keep_alive: False
[0m00:59:39.996210 [info ] [MainThread]:   host: None
[0m00:59:39.996210 [info ] [MainThread]:   port: None
[0m00:59:39.996210 [info ] [MainThread]:   proxy_host: None
[0m00:59:39.996210 [info ] [MainThread]:   proxy_port: None
[0m00:59:39.996210 [info ] [MainThread]:   protocol: None
[0m00:59:39.996210 [info ] [MainThread]:   connect_retries: 1
[0m00:59:39.996210 [info ] [MainThread]:   connect_timeout: None
[0m00:59:39.996210 [info ] [MainThread]:   retry_on_database_errors: False
[0m00:59:39.996210 [info ] [MainThread]:   retry_all: False
[0m00:59:39.996210 [info ] [MainThread]:   insecure_mode: False
[0m00:59:39.996210 [info ] [MainThread]:   reuse_connections: True
[0m00:59:39.996210 [info ] [MainThread]: Registered adapter: snowflake=1.9.0
[0m00:59:40.357154 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m00:59:40.419638 [debug] [MainThread]: Using snowflake connection "debug"
[0m00:59:40.419638 [debug] [MainThread]: On debug: select 1 as id
[0m00:59:40.419638 [debug] [MainThread]: Opening a new connection, currently in state init
[0m00:59:41.782808 [debug] [MainThread]: SQL status: SUCCESS 1 in 1.360 seconds
[0m00:59:41.798260 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m00:59:41.798260 [info ] [MainThread]: [31m2 checks failed:[0m
[0m00:59:41.798260 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Data Engineering\DBT Projec\DBT\dbt_project.yml> not found

[0m00:59:41.798260 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m00:59:41.819295 [debug] [MainThread]: Command `dbt debug` failed at 00:59:41.818304 after 2.64 seconds
[0m00:59:41.823281 [debug] [MainThread]: Connection 'debug' was left open.
[0m00:59:41.823411 [debug] [MainThread]: On debug: Close
[0m00:59:42.250818 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021DE5CAB950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021DE5C8BD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021DE773A480>]}
[0m00:59:42.250818 [debug] [MainThread]: Flushing usage events
[0m00:59:43.220123 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:29:50.077795 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C27C76EE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C27ECB17F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C27ECB3320>]}


============================== 01:29:50.087973 | e971a175-5675-44a8-915d-6ee3e6c3215a ==============================
[0m01:29:50.087973 [info ] [MainThread]: Running with dbt=1.10.3
[0m01:29:50.087973 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mukun\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m01:29:50.087973 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Data Engineering\DBT Projec\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:29:50.087973 [debug] [MainThread]: Command `dbt run` failed at 01:29:50.087973 after 0.20 seconds
[0m01:29:50.087973 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C27F0D3200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C27C76EE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C27F335520>]}
[0m01:29:50.087973 [debug] [MainThread]: Flushing usage events
[0m01:29:51.148201 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:14:12.663389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2408D4650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A23F8D2E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A240B003B0>]}


============================== 00:14:12.679011 | 9a9f61f3-9701-4e53-91ae-1a1a416d3e1b ==============================
[0m00:14:12.679011 [info ] [MainThread]: Running with dbt=1.10.3
[0m00:14:12.679011 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mukun\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run --model src_tags', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:14:12.679011 [warn ] [MainThread]: [[33mWARNING[0m]: Deprecated functionality
Usage of `--models`, `--model`, and `-m` is deprecated in favor of
`--resource-type model --select`
[0m00:14:12.679011 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'deprecation', 'label': '9a9f61f3-9701-4e53-91ae-1a1a416d3e1b', 'property_': 'warn', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2405DF560>]}
[0m00:14:12.679011 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Data Engineering\DBT Projec\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:14:12.679011 [warn ] [MainThread]: [[33mWARNING[0m][DeprecationsSummary]: Deprecated functionality
Summary of encountered deprecations:
- ModelParamUsageDeprecation: 1 occurrence
To see all deprecation instances instead of just the first occurrence of each,
run command again with the `--show-all-deprecations` flag. You may also need to
run with `--no-partial-parse` as some deprecations are only encountered during
parsing.
[0m00:14:12.679011 [debug] [MainThread]: Command `dbt run` failed at 00:14:12.679011 after 0.20 seconds
[0m00:14:12.679011 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A23DEE0B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2402E05F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A240675F40>]}
[0m00:14:12.679011 [debug] [MainThread]: Flushing usage events
[0m00:14:13.663786 [debug] [MainThread]: An error was encountered while trying to flush usage events
